### ISSUE TITLE
Pupil detection ROI setting behaves inconsistently, not always keeping 4:3 aspect ratio when it should

### ISSUE THREAD

**Issue by kheki4** [sasfog/Open-PupilEXT#10]
Pupil detection ROI is not 4:3 aspect ratio when initialized by user interatsion via Pupil Detection ROI menu/30% or 60% image area proportional size. They should not set the size in both x and y axes in e.g. 0.3 proportion, but only set one of them, and force 4:3 aspect ratio of the pupil detection ROI rectangle to the other dimension. VideoView code should be inspected for any inconsistency regarding the setting/modification of pupil detection ROI size. 

Pupil detection ROI size should always keep 4:3 aspect ratio, except if the user holds down the Alt key during resizing via mouse. this way, non-4:3 AR ractangles should be also accepted if user hits accept, but the GUI should not be misleading regarding the aspect ratio.

**Comment by sasfog** [comment]
```

- [ ] Detection ROI RESET button does not respect 4:3 aspect ratio.
- [ ] Detection ROI 30% width does not respect 4:3 aspect ratio.
- [ ] Detection ROI 60% width does not respect 4:3 aspet ratio.
- [ ] Change reset button icon to something more suitable. 
- [ ] Implement Discard button.
- [ ] Only show AutoParam ROI if pupil detection ROI is displayed. Disable checking AutoParam ROI if pupil detection ROI is turned off.

```
