### ISSUE TITLE
Cannot change image playback FPS

### ISSUE THREAD

**Issue by kheki4** [sasfog/Open-PupilEXT#2]
Even if the user specifies playback FPS in its combobox, it does not change actual playback FPS in ImagePlaybackControlDialog, but instead playback is going on at maximal speed

**Comment by sasfog** [comment]
During my attempt to reproduce the bug, I've noticed that sometimes the playback FPS changed, and sometimes it did not.

With further testing I've managed to identify the exact cause of the issues, and found two bugs:

**When user changed FPS setting to 0, any further changes to the FPS setting was ignored.**

1. For example, user could change FPS from 20 to 10, and playback speed changed.
2. User could then change FPS from 10 to 1, and playback speed changed.
3. User could then change FPS from 1 to 0, and playback speed changed.
4. However when user tried to change FPS from 0 to any other value, playback speed remained unchanged.

**Changing FPS setting to the value the dialog was initially started with also resulted in unchanged playback speed.**

1. For example, user opens image folder and FPS is set to 1.
2. User could then change FPS from 1 to 10, and playback speed changed.
3. User could then change FPS from 10 to 5, and playback speed changed.
4. However, when user changed to FPS to the initial 1 value, playback speed remained unchanged.
