### ISSUE TITLE
When opening an image set with different aspect ratio than the one used last time, pupilEXT should set pupil detection ROIs with respect to the aspect ratio of the ROI used last time, not just use the same rationally determined values for X, Y, WIDTH and HEIGHT

### ISSUE THREAD

**Issue by kheki4** [sasfog/Open-PupilEXT#63]
Problem: When we load a new image file, with different aspect ration than the one we loaded last time, the pupil detection ROI will be read from its last state, which is expressed in rational /proportional /float values, related to image size total x and y. Now if we scale the ROI by relying on the last used rational values, the ROI will be distorted.

Work around suggestion 1: for loading pupil detection ROIs on newly opened image sets, the last used rational value for X, Y and WIDTH should be used, and for the HEIGHT a new rational value should be generated, based on the discrete X:Y ration that was saved alongside the rational value into Qt persistent storage. This way, we are keeping the last used aspect ratio of the ROI (whatever is was), while the last used relative/"rational" ROI x, y and width are respected. 
Plus failsafe measure: if the newly calculated ROI would not fit the new image - e.g. width is OK, but height would not fit (due to a much wider image size than the one last used) -  then the y offset should be shrinked towards zero until the newly calculated ROI fits in to the new image on the y axis. If y is already 0 but the ROI still does not fit, the ROI should be shrinked to exactly match the height of the new image with 0 y offset and height equal to the image height.
Plus comfortability: the x and y offset values in the newly calculated ROI should be corrected by the amount we change in the size of rectangle. (e.g. when we change the size of the rectangle, x and y should be changed too, in order to keep the resized ROI center at the same rational x and y coordinates in the image.

Work around suggestion 2 (not recommended): use boolean to flag is the ROI is keeping 4:3 or not, and save the property into Qt persistent storage. When loading a new image with a different size than the one last used, rely on this bool: If it is false, just use the same rational values that were saved (= no need to keep the last used aspect ratio). If it is true, calculate in a similar way as described above in suggestion 1.

**Comment by sasfog** [comment]
Suggestion 1 has been implemented in #75 the following way:

When loading a recording to playback, the program checks if the size of the loaded recording is similar to the previously opened and saved one based on the rational ROI values saved in application settings (simple comparisons). 

1. If the new recording matches the previously saved values, the pupil detection ROI remains unchanged.
2. In case the new recording has different sizes compared to the previously saved values, the program checks whether the width or the height is shorter, and uses a default value of 60% of that side as a basis for calculating the new pupil detection ROI.

- In case the shorter side is the height, the height of the pupil detection ROI will be 60% of the height and the width will be 4/3 times that.
- In case the shorter side is the width, the width of the pupil detection ROI will be 60% of the width and the height will be 3/4 times that.
