### ISSUE TITLE
Store pupil detection ROI in a rational way, and discretize only upon setting it in PupilDetection.cpp

### ISSUE THREAD

**Issue by kheki4** [sasfog/Open-PupilEXT#9]
Fix pupil detection ROI setting (rational & discrete distinction). 
Qt persistent storage should keep these in a rational fashion.
! But metasnapshots should log rational and discrete values too.

**Comment by sasfog** [comment]
Initial Pupil Detection ROI is now properly calculated. 
Clicking on start tracking keeps Pupil Detection ROI in the same place. 
Loading image with different dimensions resets Pupil Detection ROI to a 60% pre-set. 
In case image with same dimensions is opened, Pupil Detection ROI remains the same.

Only works for single camera single pupil and stereo camera single pupil currently.
